### ISSUE TITLE
no GloveWikipedia-d200-4100-top_cluster_words.csv

### ISSUE THREAD

**Issue by a200610411** [sneheshs/threat_dictionary#1]
Hi, after running the code, I got an error saying: there is no GloveWikipedia-d200-4100-top_cluster_words.csv file generated in the results folder. What could be possibly wrong? Thanks!

**Comment by sneheshs** [comment]
Can you please share the config? Please copy and paste `line 87` to `line 138` from `generate_threat_dictionary.py`. I would like to see your config. Here is an example of what was released:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5719055/225920517-b50f2fe0-9ed0-4226-8308-bf49d5498f80.png">

I am assuming the seed words files are in the proper folder `data/seedwords/` and have words separated by new lines.

**Comment by a200610411** [comment]
![image](https://user-images.githubusercontent.com/66217591/226599689-eccca394-05d0-48c3-aabe-142a18de7775.png)

I'm also attaching a screenshot of the data folder to make sure the CORPORA files were correctly placed. 

![image](https://user-images.githubusercontent.com/66217591/226599896-e343589a-4edc-4038-804c-b7b5e8462a33.png)

**Comment by sneheshs** [comment]
Line 89 specifies the dimension of the corpus we are using. For Wikipedia, it's 200d, for Twitter, it's 200d, and for common_crawl, it's 300d. 

If you look at lines [Line 148](https://github.com/sneheshs/threat_dictionary/blob/d6bd644888cebccea281824e01ed25bab1592a88/generate_threat_dictionary.py#L148), [Line 159](
https://github.com/sneheshs/threat_dictionary/blob/d6bd644888cebccea281824e01ed25bab1592a88/generate_threat_dictionary.py#L159), and [Line 171 ](
https://github.com/sneheshs/threat_dictionary/blob/d6bd644888cebccea281824e01ed25bab1592a88/generate_threat_dictionary.py#L171), they specify that the corpus needs to be in their respective folders, and names need to be consistent with how it was provided by the publishers. For your current issue, either download the matching corpus sizes or change the dimension in line 89 to match the corpus you are using. But please make sure you make changes to the Wikipedia and CommonCrawl file names as well; otherwise, you will have the same issue.

**Comment by a200610411** [comment]
Hi Sneheshs,

I tried what you suggested but still couldn't generate the output file. Could you take one more look at the code?  (sorry about the format) Directory = C:\Users\amr3422\threat_dictionary

![image](https://user-images.githubusercontent.com/66217591/227290948-bff686df-6fcb-4038-925e-0d9684d8489e.png)



``
'''

import numpy as np
import pandas as pd
import os
import nltk
from nltk.corpus import stopwords
from gensim.models import KeyedVectors
from sklearn.cluster import SpectralClustering
from sklearn.metrics.pairwise import cosine_similarity

import warnings
warnings.filterwarnings("ignore")

###################################################
###                   CONFIG                    ###
###################################################
CORPORA                 =   {'GloveWikipedia': 200, 'GloveTwitter': 200, 'GloveInternet': 300}

'''
CORPORA DIMENTIONS
Glove Twitter     25 50 100 200
Glove Wikipedia   50 100 200 300
Glove Internet    300
'''
# Defaults for experiments (using the smallest corpus)
CORPUS_DIMENSION        =   25
CORPUS 		            =   'GloveTwitter' #'GloveInternet' 'GloveTwitter' 'GloveWikipedia'

TOP_N_WORDS_PER_SEED    =   100     # Top n words you wish to generate per seed word
CLUSTER_ASSIGN_FACTOR   =   0.1     # Take 10% of the list of words to be the number of clusters
TOP_N_PER_CLUSTER       =   10      # Final top N words per cluster (not used in this paper)
EXT                     =   '.txt'
ROOT_PATH               =   'data/'
INPUT_PATH              =   ROOT_PATH + 'seedwords/'
LOAD_MODEL              =   True     # Set to false to debug (loading the model takes a long time)

if CORPUS == 'GloveWikipedia':
    path_output_type = 'glove.wiki/'
elif CORPUS == 'GloveTwitter':
    path_output_type = 'glove.twitter/'
elif CORPUS == 'GloveInternet':
    path_output_type = 'glove.internet/'
else:
    path_output_type = ''


###################################################
###         MODIFY THIS SECTION                 ###
###################################################
'''
List of files containing the seed words separated by comma ['file1', 'file2', ...]
List your seed words in the files separated by new line
Only use single word seed words (some hyphenated words are allowed as long as they exists in the corpus vocabulary)
'''
FILES                   =   ['seedword.txt']
path_output             =   'results/'
#--------------------------------------------------
## Step 1: Generate threat words clusters
STEP                    =   1
#--------------------------------------------------
## Please manually filter the clusters as indicated in the paper
STEP                    =   2
#--------------------------------------------------
## After manually filtering the clusters, generate the final threat dictionary across all corpus
#STEP                    =   3


###################################################
###                   FUNCTIONS                 ###
###################################################
def load_language_model(CORPUS):
    if CORPUS=='GloveWikipedia':
        print('Loading GloVe Wikipedia Corpus...')
        # w2v Stanford GloVe model
        filename = ROOT_PATH + '/glove.6B.' + str(CORPUS_DIMENSION) + 'd.txt'
        if not os.path.isfile(filename + '.word2vec'):
            print('GloVe Word2Vec file not found, generating...')
            from gensim.scripts.glove2word2vec import glove2word2vec
            glove2word2vec(filename, filename + '.word2vec')
            print('Completed!')
        model = KeyedVectors.load_word2vec_format(filename + '.word2vec', binary=False)
        print('Loading Done')

    elif CORPUS=='GloveTwitter': #glove.twitter.27B
        print('Loading GloVe Twitter Corpus...')
        filename = ROOT_PATH + '/glove.twitter.27B.' + str(CORPUS_DIMENSION) + 'd.txt'
        if not os.path.isfile(filename + '.word2vec'):
            print('GloVe Word2Vec file not found, generating...')
            from gensim.scripts.glove2word2vec import glove2word2vec
            glove2word2vec(filename, filename + '.word2vec')
            print('Completed!')
        model = KeyedVectors.load_word2vec_format(filename + '.word2vec', binary=False)
        print('Loading Done')

    elif CORPUS=='GloveInternet': #glove.42B
        print('Loading GloVe Common Crawl Internet Corpus...')
        # w2v Stanford GloVe model
        filename = ROOT_PATH + '/glove.42B.' + str(CORPUS_DIMENSION) + 'd.txt'
        if not os.path.isfile(filename + '.word2vec'):
            print('GloVe Word2Vec file not found, generating...')
            from gensim.scripts.glove2word2vec import glove2word2vec
            glove2word2vec(filename, filename + '.word2vec')
            print('Completed!')
        model = KeyedVectors.load_word2vec_format(filename + '.word2vec', binary=False)
        print('Loading Done')

    else:
        print('Corpus Error: Unknown Corpus')
        model = None

    return model

def load_commonwords():
    f = open(INPUT_PATH + 'stopwords_long_list.txt', 'r')
    lines = f.read().lower().split('\n')
    f.close()
    return lines

def compute_center(vec):
    return np.mean(vec, axis=0)

def rank_centermost_words(v):
    scores = cosine_similarity([compute_center(v)], v)
    sorted_list = np.argsort(scores[0])[::-1]  # [::-1] reverses the order basically go backwards 1 item at a time
    return sorted_list

def format_cluster_output_filename(filename=''):
    txtCorpus = str(CORPUS)
    txtDim = '-d' + str(CORPUS_DIMENSION)
    txtTopN = '-t' + str(TOP_N_WORDS_PER_SEED)
    txtCluster = '' # '-c' + str(TOP_N_PER_CLUSTER)
    txtFilename = '-' + filename
    
    if filename == '':
        return path_output + txtCorpus + txtDim + txtTopN + txtCluster
    else:
        return path_output + txtCorpus + txtDim + txtTopN + txtCluster + txtFilename


###################################################
###                 PREP STEPS                  ###
###################################################
if not nltk.data.find('corpora/stopwords'):
    import ssl
    try:
        _create_unverified_https_context = ssl._create_unverified_context
    except AttributeError:
        pass
    else:
        ssl._create_default_https_context = _create_unverified_https_context
    nltk.download('stopwords')

commonwords = set(stopwords.words('english')) ## common only has 179 words
custom_commonwords = load_commonwords()         ## custom has 667 words

#Make directory if doesn't exist
if not os.path.isdir(path_output):
    os.makedirs(path_output)
    

###################################################
###                 MAIN WORKFLOW               ###
###################################################
if STEP == 1:
    
    ###################################################
    ###                 LOAD MODEL                  ###
    ###################################################
    for CORPUS in CORPORA:
        CORPUS_DIMENSION = CORPORA[CORPUS]
        filename = format_cluster_output_filename('top_cluster_words') + '.csv'
        
        # Skip if file already generated
        if os.path.exists(filename):
            print(CORPUS  + ' already processed, skipping')
            continue
        
        if LOAD_MODEL:
            model = load_language_model(CORPUS)
            if model == None:
                print('Error: GloVe Model was not loaded, exiting...')
                exit()

        ###################################################
        ###              FIND TOP WORDS                 ###
        ###################################################
        final_words = []
        for file in FILES:
            print('****************** Processing ', file, " ***************************")

            # load all the words from the input file
            read_file = INPUT_PATH + file + EXT
            rf = open(read_file, 'r')
            text = rf.read()            # this reads the entire file
            lines = text.split('\n')    # separates the file into each line
            rf.close()

            # Filter out words that are not in the model
            valid_words = []
            for line in lines:
                line = line.strip()
                if line in model.vocab:
                    valid_words.append(line)

            #### Find all close words ############
            for each_word in valid_words:
                if each_word not in commonwords and each_word not in custom_commonwords:
                    result = model.most_similar(positive=[each_word], negative=[], topn=TOP_N_WORDS_PER_SEED)
                    
                    for item in result:
                        if item[0] not in commonwords and item[0] not in custom_commonwords: 
                            if item[0] not in final_words:    ## avoid duplicates
                                final_words.append(item[0])
            final_words = sorted(final_words)

        ###################################################
        ###              CLUSTER WORDS                  ###
        ###################################################
        NUM_OF_CLUSTERS = int(len(final_words) * CLUSTER_ASSIGN_FACTOR)
        # open(format_cluster_output_filename('top_words.txt'), 'w').write('\n'.join(final_words))
        # print('Total number of words: ', len(final_words))
            
        # Convert the final words into a vector embedding
        words_vector = model[final_words]

        # Clustering
        spectral = SpectralClustering(n_clusters=NUM_OF_CLUSTERS, eigen_solver='arpack', affinity="nearest_neighbors")
        spectral.fit(words_vector)
        cluster_assignments = spectral.labels_.astype(int)

        # GROUPING INTO EACH CLUSTER COLUMNS
        fw_array = [[x] for x in final_words]
        cl_array = [[x] for x in cluster_assignments]
        new_coord = np.concatenate((fw_array, cl_array), axis=1)
        df = pd.DataFrame(data=new_coord, columns=('words', 'cluster'))
        out = pd.concat({k: g.reset_index(drop=True) for k, g in df.groupby('cluster')['words']}, axis=1)

        sorted_out = out.copy()
        for col in out:
            lis = out[col].dropna().tolist()
            vec = model[lis]

            # Get words in the order of closest to the center
            sorted_list = rank_centermost_words(vec)

            for i in range(0, len(out[col])):
                if i >= len(sorted_list):
                    sorted_out[col][i] = ''
                else:
                    sorted_out[col][i] = out[col][sorted_list[i]]
                    
        sorted_out.to_csv(format_cluster_output_filename('top_cluster_words') + '.csv', index=False)

elif STEP == 2:
    print('Please review the generated words and their clusters and filter them as described in the paper with 3 or more reveiwers.')
    
elif STEP == 3:
    final_threat_dictionary = []
    all_words = {}
    
    # Load all the words from each corpus
    for CORPUS in CORPORA:
        CORPUS_DIMENSION = CORPORA[CORPUS]
        
        filename = format_cluster_output_filename('top_cluster_words') + '.csv'
        data = pd.read_csv(filename).fillna('')
        
        for col in data.iteritems():
            for word in col[1]:
                word = str(word).strip()
                if word != '':
                    if word in all_words:
                        all_words[word] += 1
                    else:
                        all_words[word] = 1
          
    # Select words that are in all the corpora       
    for word in all_words:
        if all_words[word] == len(CORPORA):
            final_threat_dictionary.append(word)
    final_threat_dictionary = sorted(final_threat_dictionary)
    
    ## SAVE THE FINAL DICTIONARY
    print('Total number of words: ', len(final_threat_dictionary))
    open(path_output + 'final_dictionary.txt', 'w').write('\n'.join(final_threat_dictionary))
`

**Comment by sneheshs** [comment]
The current code is set to `STEP = 2`. Did you complete `STEP = 1`?
Also, can you please share the command line output of the code?

**Comment by a200610411** [comment]
Hi Sneheshs,

I may have some misunderstandings about how to use the "Modify This Section" feature. Should I only execute one step at a time and comment out the other two steps? It doesn't seem right to simply uncomment all three steps and run the code all at once.

So here is what I did. I commented STEP 2 and 3 and only ran STEP 1. 

![Screenshot 2023-03-27 130119](https://user-images.githubusercontent.com/66217591/228027367-97745b57-d6b3-4be5-9b51-0111cd26ea5e.png)

This is an error I got. 
![Screenshot 2023-03-27 130212](https://user-images.githubusercontent.com/66217591/228027539-b609a1fb-dec3-4d6c-8ac2-6cc07c63a4ec.png)

At last, is this the command line output of the code you were referring to? 
![Screenshot 2023-03-27 130310](https://user-images.githubusercontent.com/66217591/228027825-9995b171-a4b5-4121-b4da-07ff03c35652.png)

Thank you so much! Really appreciate your help!

**Comment by sneheshs** [comment]
1. It is correct that you would comment out the other steps and only chose 1 step at a time.
2. The error message clearly indicates that you have a version of the Gensim that is new and no longer supports the APIs we used. As indicated in the instructions, please make sure that you follow the version information correctly otherwise we cannot guarantee it will work on your end: (Python version and gensim version 3.7.0 --> you have 4.0.0)
<img width="854" alt="image" src="https://user-images.githubusercontent.com/5719055/228059627-cf2d4272-22af-4afd-9151-1c75123d350b.png">
3. Command line (terminal) output means where you ran your code and the where the error messages/ success messages were printed. In Spyder, I guess it is called the console.

**Comment by a200610411** [comment]
Hi Sneheshs, 

I think I can successfully run the code. However, when I tried different seed words (e.g., "Authority, Totalitarian, Dominate"), a lot of times I got an error: "ValueError: need at least one array to concatenate". I was wondering if you have any insights on this. 

Also, do you know how the code/gLove in general deals with seed words with the same linguistic root (e.g., happy, happiness)? Should I simply put one word, or put both words? 

Thank you so much!!!!

Xian Zhao

**Comment by sneheshs** [comment]
I am not sure. I am assuming your seed words file has each word as a single word in a new line and not comma separated. I'd also recommend making all your words lowercase.

I think they are considered different words but they should be close in distance in the embedding.
